### ISSUE TITLE
Add Zimbra Talk section

### ISSUE THREAD

**Issue by mogsdad** [Zimbra/adminguide#71]
In 8.8.6, Zimbra Talk was documented via a wiki entry, https://wiki.zimbra.com/wiki/Talk_V2_Admin_Guide#What_is_Zimbra_Talk_V2.

The adoc source for this needs to be reviewed and added to the admin guide. See attachment.
[zimbra_talk_v2_documentation.zip](https://github.com/Zimbra/adminguide/files/2238844/zimbra_talk_v2_documentation.zip)

**Comment by gordyt** [comment]
On Jul 29, 2018 09:31, David Bingham <notifications@github.com> wrote:In 8.8.6, Zimbra Talk was documented via a wiki entry, https://wiki.zimbra.com/wiki/Talk_V2_Admin_Guide#What_is_Zimbra_Talk_V2.
The adoc source for this needs to be reviewed and added to the admin guide. See attachment.
zimbra_talk_v2_documentation.zip

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.



This message and any attachment may contain information that is confidential and/or proprietary. Any use, disclosure, copying, storing, or distribution of this e-mail or any attached file by anyone other than the intended recipient is strictly prohibited. If you have received this message in error, please notify the sender by reply email and delete the message and any attachments. Thank you.

**Comment by mogsdad** [comment]
Added to develop branch with https://github.com/Zimbra/adminguide/commit/c3d39afb0d39c4b5c5f229665e86145b29bad877
